### ISSUE TITLE
Unnecessary vertical scroll apears in Chrome

### ISSUE THREAD

**Issue by eugenp** [syntaxhighlighter/syntaxhighlighter#152]
This was being tracked here: 
https://bitbucket.org/alexg/syntaxhighlighter/issue/177/superfluous-vertical-scrollbars-in-chrome
The issue is still occurring with Chrome: 22.0.1229.79

**Comment by sglienke** [comment]
Still exists and very annoying.

**Comment by crazy-max** [comment]
You can add this in a CSS :

```css
.syntaxhighlighter {
  overflow-y: hidden !important;
}
```
