### ISSUE TITLE
Double click in Version 3 remove the Striped background and syntax highlight

### ISSUE THREAD

**Issue by LeonardoGentile** [syntaxhighlighter/syntaxhighlighter#200]
I' ve styled sh modifying the `.line.alt2` class:

``` css
.syntaxhighlighter .line.alt1 {
  background-color: white !important;
}
.syntaxhighlighter .line.alt2 {
  background-color: #f8f8f8 !important;
}
```

This produce a striped background, similar to the one available in Version 2. The problem is that when double-clicking to select all the code (that IMO doesn't work very smoothly) it also  remove the custom background color and  any code  highlight. To let the striped background and the font color to come back I have to click anywhere outside the sh element.
