### ISSUE TITLE
Not aligned with the line number

### ISSUE THREAD

**Issue by a0000778** [syntaxhighlighter/syntaxhighlighter#290]
English:
on Linux(Ubuntu 12.04)
if code have chinese char
will not aligned with the line number

Not aligned:
Chrome 32.0.1700.107
Opera 12.16
aligned:
FireFox 27.0
# 

中文(Chinese)：
在Linux(Ubuntu 12.04)上
如果代碼包含中文字元
將導致行號不對齊的狀況

不對齊：
Chrome 32.0.1700.107
Opera 12.16
對齊：
FireFox 27.0
# 

http://i.imgur.com/YeWfPng.png
http://code.a0000778.coms.hk/#plugin/php!page=plugin/PHP/lib_DB

**Comment by ngetchell** [comment]
I am having the same issue as well on Firefox but it is more pronounced. 

![2](https://cloud.githubusercontent.com/assets/813422/7813462/553160a0-0389-11e5-9f0d-2f9d1492c2e4.PNG)
![1](https://cloud.githubusercontent.com/assets/813422/7813463/5533c584-0389-11e5-88d5-b61280cd8c43.JPG)

**Comment by drdhaval2785** [comment]
Same issue with me on firefox.
See https://github.com/drdhaval2785/github_issue_backup/issues/19#issuecomment-105023223.

But I guess that it has something to do with CSS or some specific HTML tags.
In my example, the code is within a div.

Purely posting the code without the div tags seem to have correct output.

**Comment by Amith211** [comment]
I had this misalign issue too, although it wasn't caused by Chinese letters. I fixed this issue on my site by making the following modification to shCore.css: 
`vertical-align: baseline !important;` to 
`vertical-align: top !important;`

**Comment by mrcuijt** [comment]
It's worked for me

```css
body {
    font-size:14px !important;
    font-family: "Courier New", Helvetica, Geneva, Arial, sans-serif !important;
}
 
.code > .container > .line {
    height: 1em !important;
    line-height: 1em !important;
    font-family: "courier new" !important;
}
 
.code > .container > .line > code {
    height: 1em !important;
    line-height: 1em !important;
    font-family: "courier new" !important;
}
 
.code > .container > .line > .java, .code > .container > .line > .js {
    height: 1em !important;
    line-height: 1em !important;
    font-family: "courier new" !important;
}
 
.gutter > .line {
    height: 1em !important;
    line-height: 1em !important;
    font-family: "courier new" !important;
}
```
![modify](https://user-images.githubusercontent.com/18755157/57996410-e4779b80-7af9-11e9-9f37-475daa080ae6.png)
