### ISSUE TITLE
underscores not showing if on last line of code in some browsers/OS

### ISSUE THREAD

**Issue by metulburr** [syntaxhighlighter/syntaxhighlighter#406]
Im running on Ubuntu 16.04 with chrome and firefox. 

The last line of code if has underscores do not show
[Imgur](http://i.imgur.com/4NiTB7z.png)

**Comment by mateuszzz88** [comment]
I have the same problem on ubuntu 16.10

**Comment by pablinos** [comment]
I've seen this problem with Firefox on Debian. I managed to fix it by adding some padding to the containing div

```css
.syntaxhighlighter table td.code .container {
    padding-bottom: 2px !important;
}
````

It's a bit of a hack and I think the real issue is related to font rendering, but it solves the problem until a better fix is found.
